# Generated by Django 3.1.7 on 2021-04-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0002_auto_20210405_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='genres_list',
            field=models.TextField(default=''),
        ),
    ]
