# Generated by Django 3.1.7 on 2021-04-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0003_webtoon_genres_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='scale_loss',
            field=models.FloatField(default=0),
        ),
    ]
