# Generated by Django 3.1.7 on 2021-03-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('webtoon_number', models.AutoField(primary_key=True, serialize=False)),
                ('webtoon_name', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('webtoon_writer', models.CharField(max_length=50)),
                ('thumbnail_url', models.TextField()),
                ('webtoon_score', models.FloatField()),
                ('overview_morph', models.TextField()),
                ('genres', models.ManyToManyField(related_name='webtoons', to='recommends.Genre')),
            ],
        ),
    ]
