# Generated by Django 3.1.7 on 2021-03-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='serialized_day',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='webtoon_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='webtoon_platform',
            field=models.TextField(default=''),
        ),
    ]
