# Generated by Django 3.1.7 on 2021-04-01 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommends', '0002_auto_20210323_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='users_webtoon',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False)),
                ('users_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('webtoons_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_webtoon', to='recommends.webtoon')),
            ],
        ),
    ]
