# Generated by Django 3.1.7 on 2021-04-05 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0001_initial'),
        ('recommends', '0003_auto_20210401_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webtoon',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='webtoon',
            name='users_webtoon',
        ),
        migrations.AlterField(
            model_name='like',
            name='webtoons_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_webtoon', to='webtoons.webtoon'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Webtoon',
        ),
    ]
