# Generated by Django 3.1.7 on 2021-04-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0004_auto_20210405_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
